---
title: A presentation with Polylux via Quarto
author:
  - name: Author One
    affiliations:
      - name: Harvard University
  - name: Author Two
    affiliations:
      - name: Yale University
date: today
format:
  projector-typst:
    keep-typ: true
bullet-incremental: true
---

## Introduction

*TODO* Create an example file that demonstrates the formatting and features of your format.

## More Information

You can learn more about creating custom Typst templates here:

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>

# Features

## Incremental Lists

- First item
- Second item
- Third item

## Non-Incremental

:::{.nonincremental}

- one-th
- two-th
- three-th

:::

## And manual pauses

Sometimes you write text

. . .

that needs time to be ready


---

An untitled slide?

Yes! It's possible with `---`.

## Split slides

::::  {.columns align=top .onlytextwidth}

::: {.column width="40%" align=center}
contents left
:::

::: {.column width="60%"}
contents right
:::

::::


## Split slides, fixed width and centered

:::: {.columns align=center totalwidth=20em}

::: {.column width="40%"}
contents...
:::

::: {.column width="60%" align=bottom}
contents...
:::

::::


## Callouts: Mapped from Beamer

We can use the heading values to control callouts, like so:

### Caution! {.alert}

This is an important warning.

### Try This {.example}

This demonstrates something useful.

### Note

Plain information.

## Callouts: Custom to this template

And here's a little extra flair

### Tip {.tip}

A tip for the viewer

### Reminder {.reminder}

A thing to remember

### Warning! {.warning}

For a little less caution than an alert



## Using Typst functions

explain here
